Changing site layout, by serving only angular
Jade templates are removed, and server side rending will be disabled for
the moment; until csrf tokens are required probably.

Next, a message service and message box directive were written and
inserted into the content controller. However, there seems to be still
an error, which gives the following error message:

TypeError: Object #<Object> has no method 'match'